---
  - name: Install packages on hosts
    hosts: frontend
    #connection: local
    become: yes

    tasks:
    - name: Install nginx packages
      ansible.builtin.package:
        name: nginx
        state: present
