---
  - name: variables in ansible 
    hosts: localhost
    connection: local
    vars:
      COURSE: AWS
      DURATION: 200HR
      TRAINER: Sivakumar
    
    tasks:
    - name: print AWS devops course info
      ansible.builtin.debug:
        msg: "Hello {{ COURSE }}, course duration: {{ DURATION }}, Trainer: {{ TRAINER }}"

    - name: print AWS course details
    vars:
      COURSE: Ansible
      DURATION: 10HR
      TRAINER: Sivakumar
      ansible.builtin.debug:
        msg: "Hello {{ COURSE }}, course duration: {{ DURATION }}, Trainer: {{ TRAINER }}"