---
  - name: variables in ansible 
    hosts: local
    connection: local
    vars:
      COURSE: Ansible
      DURATION: 10HR
      TRAINER: Sivakumar
    
    tasks:
    - name: print devops course info
      ansible.builtin.debug:
        msg: "Hello {{ COURSE }}, course duration: {{ DURATION }}, Trainer: {{ TRAINER }}"