---
  - name: print variable from user prompt
    hosts: localhost
    connection: local

    vars_prompt:
    - name: usernmae
      prompt: Please enter usernmae
      private: false

    - name: password
      prompt: please enter password
      private: true

    tasks:
    - name: print course details
      ansible.builtin.debug:
        msg: "User name is {{ usernmae }} and password is {{ password }}"
