---
  - name: print vars from inventory vars_files
    hosts: local
    connection: local

    tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "I am learning {{ Course }}, Duration: {{ Duration }}, Trainer: {{ Trainer }}"