---
  - name: print vars from inventory vars_files
    hosts: localhost
    connection: local

    tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "Hello team {{ Course }}, Duration: {{ Duration }}, Trainer: {{ Trainer }}"