---
  - name: validate when condition in ansible playbook
    hosts: test

    vars:
      NUMBER: 666

    tasks:
    - name: check a number is less than 100
      ansible.builtin.debug:
        msg: "{{ NUMBER }} is less than 100"
      when: NUMBER < 100

    - name: check a num is greater than 100
      ansible.builtin.debug:
        msg: "{{ NUMBER }} is greter than 100"
      when: NUMBER > 100