---
  - name: ansible lopps
    hosts: local
    connection: local
    tasks:
    - name: print loop members
      ansible.builtin.debug:
        msg: "Member is : {{ item }}"
      loop:
      - 123
      - abcd
      - Ramesh