---
  - name: ansible functions/filters
    hosts: local
    connection: local
    vars:
    - persons: "Ramesh,Raheem,Joseph"
    tasks:
    - name: ansible an undefined variable usinf filter
      ansible.builtin.debug:
        msg: "Hello, {{ person | default('Ramesh') }}"

    - name: print string list
      ansible.builtin.debug:
        msg: "Hello, {{ persons | split(',') }}"

    - name: convert map/dict to list
      vars:
        course:
          name: devops
          duration: 10HR
          trainer: siva
      ansible.builtin.debug:
        msg: "course info: {{course | dict2items }}"

    - name: convert list to dict/map
      vars:
        course:
        - {'key': 'name', 'value': 'devops'}
        - {'key': 'duration', 'value': '10HR'}
        - {'key': 'trainer', 'value': 'siva'}
      ansible.builtin.debug:
        msg: "course info: {{course | items2dict }}"