---
  - name: ansible functions/filters
    hosts: local
    connection: local
    tasks:
    - name: ansible an undefined variable usinf filter
      ansible.builtin.debug:
        msg: "Hello, {{ person | default('Ramesh') }}"