---
  - name: shell vs command 
    hosts: local
    connection: local
    tasks:
    - name: execute command in ansible
      ansible.builtin.command: "ls -ltr > /tmp/output.txt"
      register: output
      ignore_errors: yes

    - name: print command output
      ansible.builtin.debug:
        msg: "{{ output }}"

    - name: execute shell in ansible
      ansible.builtin.shell: "ls -ltr > /tmp/output.txt"
      register: output_shell

    - name: print shell output
      ansible.builtin.debug:
        msg: "{{ output_shell }}"