---
  - name: install nginx
    hosts: dynamic_frontend
    serial: 5
    become: yes

    tasks:
    - name: install nginx server
      ansible.builtin.dnf:
        name: nginx
        state: installed
    - name: run nginx
      ansible.builtin.service:
        name: nginx
        state: started