---
  - name: create ec2 instances and associate with route53
    hosts: local
    connection: local
    vars:
      instances:
      - mysql
      - backend
      - frontend
      vpc_subnet_id: "subnet-0044dfb84e469a1f5"
      security_group_id: "sg-0a30f9b8a8f6adb2b"
      image_id: "ami-09c813fb71547fc4f"
      zone: "rameshaws.site"

    tasks:
    - name: create ec2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        instance_type: t3.micro
        security_group: "{{ security_group_id }}"
        image_id: "{{ image_id }}"
        tags:
          Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output

    # - name: print ec2 output
    #   ansible.builtin.debug:
    #     msg: "{{ ec2_output }}"

    - name: create r53 records
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ item.item }}.{{ zone }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address}}"
        wait: true
        overwrite: true
      loop: "{{ ec2_output.results }}"

    - name: create r53 records for frontend server
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ zone }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address}}"
        wait: true
        overwrite: true
      loop: "{{ ec2_output.results }}"
      when: item.item == "frontend"